.TH GRML2HD-UTILS 8
.SH NAME
remove-packages-server \- utilities for a grml-system on harddisk
.SH SYNOPSIS
.B remove-packages-server
.SH DESCRIPTION
This manual page documents briefly the
.B grml2hd-utils
suite.
.PP
\fBremove-packages-server\fP is a script which will remove server packages on your grml-system. This
script is useful if you want to use your grml-system as a plain workstation.

.SH SEE ALSO
.BR grml2hd (8).
.br
.SH AUTHOR
grml2hd-utils was written by Michael Prokop <mika@grml.org>.
.PP
This manual page was written by Michael Prokop <mika@grml.org>,
for the Debian project (but may be used by others).
